# Categorical Encodings

Categorical encoding is the process of converting categorical variables (non-numeric data) into numerical representations that machine learning algorithms can work with.

## 1. One-Hot Encoding

One-Hot Encoding converts a categorical variable with n unique values into n binary columns (0s and 1s). Each value is represented with a binary vector where only one position contains 1 (hot) and all others contain 0 (cold).

**When to use:** Best for nominal categorical variables with few unique values. Commonly used in tree-based models and neural networks.

**Example:** Color (Red, Green, Blue) → [1,0,0], [0,1,0], [0,0,1]

### Python Implementation

In [9]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from category_encoders import TargetEncoder, BinaryEncoder

# Sample Data
data = pd.DataFrame({
    'Color': ['Red', 'Blue', 'Green', 'Red', 'Blue', 'Green'],
    'Target': [1, 0, 1, 1, 0, 1]
})

# One-Hot Encoding using pandas
one_hot_encoded = pd.get_dummies(data['Color'], prefix='Color')
print("One-Hot Encoding (pandas):")
print(one_hot_encoded)

# Alternative: Using sklearn
encoder = OneHotEncoder(sparse_output=False)
one_hot_sklearn = encoder.fit_transform(data[['Color']])
print("\nOne-Hot Encoding (sklearn):")
print(one_hot_sklearn)

One-Hot Encoding (pandas):
   Color_Blue  Color_Green  Color_Red
0       False        False       True
1        True        False      False
2       False         True      False
3       False        False       True
4        True        False      False
5       False         True      False

One-Hot Encoding (sklearn):
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


## 2. Label Encoding

Label Encoding converts categorical variables into integer labels (0, 1, 2, ..., n-1). Each unique category is assigned a unique integer value.

**When to use:** Suitable for ordinal categorical variables where there's a natural ordering (e.g., Low, Medium, High). Also used in tree-based models.

**Example:** Color (Red, Green, Blue) → 0, 1, 2

### Python Implementation

In [10]:
# Label Encoding using sklearn
label_encoder = LabelEncoder()
label_encoded = label_encoder.fit_transform(data['Color'])
print("Label Encoding:")
print(label_encoded)
print("Mapping:", dict(zip(label_encoder.classes_, label_encoder.transform(label_encoder.classes_))))

# Alternative: Using pandas
label_encoded_pandas = pd.Categorical(data['Color']).codes
print("\nLabel Encoding (pandas - using codes):")
print(label_encoded_pandas)

Label Encoding:
[2 0 1 2 0 1]
Mapping: {'Blue': np.int64(0), 'Green': np.int64(1), 'Red': np.int64(2)}

Label Encoding (pandas - using codes):
[2 0 1 2 0 1]


## 3. Target Encoding (Mean Encoding)

Target Encoding replaces each category with the mean value of the target variable for that category. It captures the relationship between the categorical variable and the target.

**When to use:** Effective for high-cardinality categorical variables. Works well with linear models and regularized models.

**Example:** If 'Red' has target values [1, 1], the encoding is the mean = 1.0

### Python Implementation

In [11]:
# Target Encoding using category_encoders
# Note: Using manual pandas implementation due to sklearn compatibility
# target_encoder = TargetEncoder()
# target_encoded = target_encoder.fit_transform(data['Color'], data['Target'])

# Manual implementation using pandas (recommended)
target_means = data.groupby('Color')['Target'].mean()
target_encoded = data['Color'].map(target_means)
print("Target Encoding (Mean Encoding):")
print(target_encoded.values)

Target Encoding (Mean Encoding):
[1. 0. 1. 1. 0. 1.]


## 4. Binary Encoding

Binary Encoding first converts categories into integers (label encoding), then converts those integers to binary representations. This reduces the number of features compared to one-hot encoding.

**When to use:** Good for high-cardinality categorical variables where you want to reduce dimensionality. Works well with tree-based models.

**Example:** Color (Red, Green, Blue) → 0(binary: 00), 1(binary: 01), 2(binary: 10)

### Python Implementation

In [12]:
# Binary Encoding using category_encoders
binary_encoder = BinaryEncoder()
binary_encoded = binary_encoder.fit_transform(data['Color'])
print("Binary Encoding:")
print(binary_encoded)

# Alternative: Manual implementation
label_encoded_vals = label_encoder.fit_transform(data['Color'])
binary_encoded_manual = pd.DataFrame(
    [list(format(int(x), '02b')) for x in label_encoded_vals],
    columns=['Bit_1', 'Bit_2']
)
print("\nBinary Encoding (manual):")
print(binary_encoded_manual)

Binary Encoding:
   Color_0  Color_1
0        0        1
1        1        0
2        1        1
3        0        1
4        1        0
5        1        1

Binary Encoding (manual):
  Bit_1 Bit_2
0     1     0
1     0     0
2     0     1
3     1     0
4     0     0
5     0     1
