## Tensors in Pytorch

A Pytorch Tensor is basically the same as a NumPy array. This means it does not know anything about deep learning or computational graphs or gradients and is just a generic n-dimensional array to be used for arbitrary numeric computation. However, the biggest difference between a NumPy array and a PyTorch Tensor is that a PyTorch Tensor can run on either CPU or GPU. To run operations on the GPU, just cast the Tensor to a cuda datatype using:

```python
device = torch.device("cpu")
```


To create random input and output data, where `N` is batch size, `D_in` is input dimension, `H` is hidden dimension, and `D_out` is output dimension:

```python
N, D_in, H, D_out = 32, 100, 10, 2

x = torch.randn(N, D_in, device=device, dtype=torch.float)    #where x is a tensor
```

In the above example, `x` can be thought of as a random feature tensor as an input to a model. We will see how to create tensors, different attributes, and operations on a tensor in this article.

## <br>How to create a Tensor?
You can create a tensor using some simple lines of code as shown below.

In [2]:
import torch

V_data = [1, 2, 3, 4, 5]
V = torch.tensor(V_data)

print(V)

# You can also create a tensor of random data with a given dimensionality like:
x = torch.randn(3, 4, 5)
x

tensor([1, 2, 3, 4, 5])


tensor([[[ 0.4207, -0.5644, -0.5698, -1.2575,  0.5989],
         [-1.2561,  0.3133, -0.1052,  0.6413,  0.4435],
         [ 1.0040,  0.0178, -0.0877, -1.0051,  0.7445],
         [ 1.1376, -0.9428, -0.2414,  0.8945,  1.4906]],

        [[ 0.3820, -0.7279, -0.2648,  1.9532,  0.6073],
         [ 0.7765, -1.3859, -0.8251,  1.6833, -0.9906],
         [-1.1989,  0.5775,  0.4785, -1.1045,  0.5058],
         [ 0.2767, -0.9262,  0.9927,  1.1878, -1.9918]],

        [[ 0.4965,  1.2075, -1.0583, -0.4868,  0.7357],
         [-0.1184, -0.5207,  0.7329, -0.1622, -0.2014],
         [ 2.1269,  0.8173, -1.6402, -1.1488,  2.6282],
         [ 0.0609, -0.5272, -0.8947,  0.4061, -1.6193]]])

In [3]:
# torch.zeros(): Creates a new Tensor with all elements, initialized as zeros
z = torch.zeros([3, 3], dtype=torch.int32)
print(z)

# toch ones
z = torch.ones([3, 3])
print(z)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


- torch.full() and torch.full_like():  These functions return a Tensor of the required size filled with required fill_value provided. The complete prototype for torch.full() is:

In [ ]:
# example of torch.full()
newTensor= torch.full((4, 3), 3.14, dtype= torch.float32)
print(newTensor)

# Example for torch.full_like()
x = torch.full_like(newTensor, 3.24, dtype=None)
print(x)

tensor([[3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400],
        [3.1400, 3.1400, 3.1400]])
tensor([[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]], dtype=torch.int16)


## Tensor Attributes

Every `torch.Tensor` has three core attributes: **dtype**, **device**, and **layout**.

---

### `torch.dtype` — Data Type
Defines what kind of numbers the tensor holds (e.g. `float32`, `int64`, `bool`). PyTorch supports 12 data types in total.

---

### `torch.device` — Where it lives
Specifies whether the tensor is on **CPU** or **GPU (CUDA)**.

```python
torch.device('cuda:0')  # GPU #0
# → device(type='cuda', index=0)

torch.device('cpu')     # CPU
```

> If no device index is given, it refers to the **currently active device**.

---

### `torch.layout` — Memory Layout
Controls how tensor data is physically stored in memory. Two options:

#### 1. `torch.strided` *(default — dense tensors)*
The standard layout. **Strides** define how many memory steps to take to move to the next element in each dimension.

```python
x = torch.Tensor([[1, 2, 3, 4],
                  [5, 7, 8, 9]])
x.stride()  # → (4, 1)
```
- Next **row** → jump **4** elements
- Next **column** → jump **1** element

#### 2. `torch.sparse_coo_tensor` *(sparse tensors)*
Efficient for tensors with mostly zeros. Stores only **non-zero values** and their **indices** (COO = Coordinate format).

```python
i = [[0, 1, 1],   # row indices
     [2, 0, 2]]   # col indices
v = [3, 4, 5]     # non-zero values

s = torch.sparse_coo_tensor(i, v, (2, 3))
# tensor(indices=tensor([[0, 1, 1],
#                        [2, 0, 2]]),
#        values=tensor([3, 4, 5]),
#        size=(2, 3), nnz=3, layout=torch.sparse_coo)
```
A 2×3 matrix with only 3 stored values instead of 6 — saves memory when most elements are zero.

## <br>Tensor operations:

In [5]:
# 1. You can add two tensors like matrix addition.
x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])
z = x + y

print(z)


# 2. Concatenates a list of tensors
x_1 = torch.randn(2, 5)
y_1 = torch.randn(3, 5)
z_1 = torch.cat([x_1, y_1])

print(z_1)


# 3. To concatenate columns you can do the following
x_2 = torch.randn(2, 3)
y_2 = torch.randn(2, 5)

# second argument specifies which axis to concat along
z_2 = torch.cat([x_2, y_2], 1)
print(z_2)


# 4. You can reshape tensors using the .view() method as shown below.
x = torch.randn(2, 3, 4)
print(x)

# reshape to 2 rows, 12 columns
print(x.view(2, 12)) 


# 5. Returns the index of the maximum value of all elements in the input tensor.
x = torch.randn(3,3)
print((x, torch.argmax(x)))


# 6. Similar to argmax(), it returns the minimum value of all elements in the input tensor.
x = torch.randn(3,3)
print((x, torch.argmin(x)))


tensor([5., 7., 9.])
tensor([[-4.7867e-01,  1.0546e+00, -8.0450e-01,  5.1961e-01, -6.2569e-01],
        [-1.7091e+00,  6.5519e-01,  1.2717e+00,  1.1658e+00,  5.9771e-01],
        [-8.2266e-01,  3.0088e-01,  3.2636e-01,  6.2587e-02,  1.2576e-03],
        [-1.0121e+00, -7.3932e-01,  1.0118e+00, -2.4691e-01,  8.5259e-01],
        [ 3.6458e-01, -1.5583e-01, -2.2653e-01, -2.3805e+00, -3.2926e-01]])
tensor([[-1.4484, -0.9070, -1.2611,  0.1420, -1.8424, -0.6247,  0.7222,  1.5609],
        [-1.5060,  0.3445, -0.7894, -0.4998,  1.5857, -0.0129,  0.7792,  2.2214]])
tensor([[[-1.0610, -0.5734, -0.7278,  0.9433],
         [-1.7695,  0.1202, -1.3338, -1.0582],
         [-0.7232, -0.0976,  0.1648,  2.8422]],

        [[ 0.7253,  0.0536, -0.2019, -0.5893],
         [ 1.6833, -0.4494, -1.4019,  0.3073],
         [-0.3107, -0.4903, -0.4640,  0.7746]]])
tensor([[-1.0610, -0.5734, -0.7278,  0.9433, -1.7695,  0.1202, -1.3338, -1.0582,
         -0.7232, -0.0976,  0.1648,  2.8422],
        [ 0.7253,  0.0536